version: '3.8'

services:
  imagechan-front-app:
    image: node:18  # Usamos Node.js 18
    container_name:  imagechan-front-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - '8080:8080'
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    networks:
      - windows96

volumes:
   imagechan-front-app-data:

networks:
  windows96:
    external: true
    name: windows96