/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Adcard: typeof import('./components/common/adcard.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppMenuHeader: typeof import('./components/AppMenuHeader.vue')['default']
    AppMenuPopup: typeof import('./components/AppMenuPopup.vue')['default']
    Dialog: typeof import('./components/common/dialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageInput: typeof import('./components/inputs/imageInput.vue')['default']
    Login: typeof import('./components/forms/login.vue')['default']
    Post: typeof import('./components/forms/post.vue')['default']
    Postcard: typeof import('./components/common/postcard.vue')['default']
    Register: typeof import('./components/forms/register.vue')['default']
    Replycard: typeof import('./components/common/replycard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rulescard: typeof import('./components/common/rulescard.vue')['default']
    SwitchInput: typeof import('./components/inputs/switchInput.vue')['default']
    TextAreaInput: typeof import('./components/inputs/textAreaInput.vue')['default']
    TextInput: typeof import('./components/inputs/textInput.vue')['default']
    Usercard: typeof import('./components/common/usercard.vue')['default']
  }
}
